### ISSUE TITLE
Only backing up pages folder?

### ISSUE THREAD

**Issue by kerim** [ryanpcmcquen/obsidian-dropbox-backups#7]
I have four folders in my vault: pages, assets, journals, and logseq (since I use that app as well), but the plugin only seems to be backing up the pages folder?

**Comment by ryanpcmcquen** [comment]
Did you figure it out?

**Comment by kerim** [comment]
Thanks for asking. I'm not sure. There was another issue due to me having messed up the Hazel rules, so I want to make sure that this issue is unrelated. I think it is, but I can't be sure just yet. Will report back later...

**Comment by kerim** [comment]
OK. I can confirm that this is an issue. It is only backing up the pages folder.

**Comment by ryanpcmcquen** [comment]
Any errors in the console? Do you have any files with characters that Dropbox does not allow? Which folder do you open as your vault inside Obsidian?

**Comment by kerim** [comment]
The console log looks like this (just the last few rows here:

```
upload:1 Failed to load resource: the server responded with a status of 409 (Conflict)
main.ts:193 DropboxResponseError: Response failed with a 409 code
    at eval (eval at <anonymous> (app://obsidian.md/app.js:1:1195660), <anonymous>:2594:11)
eval @ main.ts:193
main.ts:138 Attempting backup to: /logseq/2021/06/28/08_08_16_012
main.ts:199 Backup to /logseq/2021/06/28/07_48_16_022 canceled!
upload:1 Failed to load resource: the server responded with a status of 409 (Conflict)
main.ts:193 DropboxResponseError: Response failed with a 409 code
    at eval (eval at <anonymous> (app://obsidian.md/app.js:1:1195660), <anonymous>:2594:11)
eval @ main.ts:193
upload:1 Failed to load resource: the server responded with a status of 409 (Conflict)
main.ts:193 DropboxResponseError: Response failed with a 409 code
    at eval (eval at <anonymous> (app://obsidian.md/app.js:1:1195660), <anonymous>:2594:11)
eval @ main.ts:193
upload:1 Failed to load resource: net::ERR_NETWORK_IO_SUSPENDED
main.ts:193 TypeError: Failed to fetch
eval @ main.ts:193
upload:1 Failed to load resource: the server responded with a status of 409 (Conflict)
main.ts:193 DropboxResponseError: Response failed with a 409 code
    at eval (eval at <anonymous> (app://obsidian.md/app.js:1:1195660), <anonymous>:2594:11)
eval @ main.ts:193
upload:1 Failed to load resource: the server responded with a status of 409 (Conflict)
main.ts:193 DropboxResponseError: Response failed with a 409 code
    at eval (eval at <anonymous> (app://obsidian.md/app.js:1:1195660), <anonymous>:2594:11)
eval @ main.ts:193
upload:1 Failed to load resource: the server responded with a status of 409 (Conflict)
main.ts:193 DropboxResponseError: Response failed with a 409 code
    at eval (eval at <anonymous> (app://obsidian.md/app.js:1:1195660), <anonymous>:2594:11)
eval @ main.ts:193
upload:1 Failed to load resource: the server responded with a status of 409 (Conflict)
main.ts:193 DropboxResponseError: Response failed with a 409 code
    at eval (eval at <anonymous> (app://obsidian.md/app.js:1:1195660), <anonymous>:2594:11)
eval @ main.ts:193
upload:1 Failed to load resource: the server responded with a status of 409 (Conflict)
main.ts:193 DropboxResponseError: Response failed with a 409 code
    at eval (eval at <anonymous> (app://obsidian.md/app.js:1:1195660), <anonymous>:2594:11)
eval @ main.ts:193
upload:1 Failed to load resource: the server responded with a status of 409 (Conflict)
main.ts:193 DropboxResponseError: Response failed with a 409 code
    at eval (eval at <anonymous> (app://obsidian.md/app.js:1:1195660), <anonymous>:2594:11)
eval @ main.ts:193
```

**Comment by ryanpcmcquen** [comment]
There is a conflict with those files, can you dig into the Network tab and get the full response?

**Comment by kerim** [comment]
Thanks for your help, but in the end I think I found a backup solution that works better for me: Arq Backup. I'm afraid I'm not so comfortable with the developer tools to be able to track down the error. (Dropbox was also using significant amounts of energy on my laptop.)

**Comment by ryanpcmcquen** [comment]
No worries, I will try to add errors to the settings page to make this type of thing easier to debug. It is likely the filenames had characters not allowed by Dropbox (I've seen that cause 409 errors before).

**Comment by ryanpcmcquen** [comment]
The main point of this plugin is to be a safeguard for Obsidian Mobile users.

**Comment by kerim** [comment]
That makes sense. I see you can turn on different plugins on mobile and desktop, so I might try it there...
